name: "publish npm"

on: push

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v2
            - name: node
              uses: actions/setup-node@v2
              with:
                  node-version: 12
                  registry-url: https://npm.pkg.github.com
    publish-gpr:
     needs: build
     runs-on: ubuntu-latest
     steps:
      - run: echo "registry=https://npm.pkg.github.com/@hirenrparghi" >> .npmrc
      - run: |
           pwd
           ls -la
           npm publish
           
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
